### ISSUE TITLE
 ItemReceivedOfferEvent and ItemReceivedBidEvent api

### ISSUE THREAD

**Issue by hongdangshao** [foundVanting/opensea-stream-go#1]
Hello, excuse me. Do you have any plan for ItemReceivedOfferEvent and ItemReceivedBidEvent api for the subscriber?

**Comment by foundVanting** [comment]
like this, https://github.com/foundVanting/opensea-stream-go/blob/main/examples/simple.go

**Comment by hongdangshao** [comment]
您的邮件已收到！请放心！

**Comment by hongdangshao** [comment]
大佬您好，请问opensea stream api的数据如何插入到clickhouse或者hbase中呢，golang小白解决不了求助。借助生产者消费者模型，可以打印出来每个解析到的相应字段，但是就是无法插入到clickhouse的数据库。也没有啥报错信息。


希望能得到大佬的指点，感谢！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "foundVanting/opensea-stream-go"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月22日(星期三) 下午3:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [foundVanting/opensea-stream-go]  ItemReceivedOfferEvent and ItemReceivedBidEvent api (Issue #1)





 
like this, https://github.com/foundVanting/opensea-stream-go/blob/main/examples/simple.go
